spring:
  datasource:
    url: jdbc:mysql://47.98.190.181:3306/xqsyw?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: wy18052712
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  profiles.active: aeolian
  ## MULTIPART (MultipartProperties)
  # 开启 multipart 上传功能
  servlet.multipart.enabled: true
  # 文件写入磁盘的阈值
  servlet.multipart.file-size-threshold: 1KB
  # 最大文件大小
  servlet.multipart.max-file-size: 200MB
  # 最大请求大小
  servlet.multipart.max-request-size: 215MB

## 文件存储所需参数
# 所有通过 REST APIs 上传的文件都将存储在此目录下

server:
  port: 8080








  thymeleaf:
    mode: LEGACYHTML5
    encoding: utf-8
    content-type: text/html
    cache: false
